version: '3'

services:
    web:
      build: ./web
      environment:
        - APACHE_RUN_USER=#1000
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      ports:
          - 8082:80
      working_dir:
        ${APP_PATH_CONTAINER}
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password  --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
          - 6082:8080
    composer:
      image: composer:1.6
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      working_dir: ${APP_PATH_CONTAINER}
